<?php
echo
"<tr>"
    ."<td>"
        .$row["crashid"]
        ."</td>"
    ."<td>"
        .$row["date"]
        ."</td>"
    ."<td>"
        .$row["time"]
        ."</td>"
    ."<td>"
        .$row["locid"]
        ."</td>"
    ."<td>"
        .$row["acclocx"]
        ."</td>"
    ."<td>"
        .$row["acclocy"]
        ."</td>"
    ."<td>"
        .$row["total_cas"]
        ."</td>"
    ."<td>"
        .$row["total_fats"]
        ."</td>"
    ."<td>"
        .$row["total_si"]
        ."</td>"
    ."<td>"
        .$row["total_mi"]
        ."</td>"
    ."<td>"
        .$row["area_speed"]
        ."</td>"
    ."<td>"
        .$row["pos_type"]
        ."</td>"
    ."<td>"
        .$row["crash_type"]
        ."</td>"
    ."<td>"
        .$row["dui"]
        ."</td>"
    ."<td>"
        .$row["drugs"]
        ."</td>"
    ."</tr>";
